name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh

  exercises:
    name: Exercises
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Install sponge
        run: sudo apt-get install moreutils
      - name: Check compatibility with current exercises
        run: bin/run-all-exercises-in-docker.sh /tmp/output
